### ISSUE TITLE
[help] Isn't Odd Big Word an instance of Num?

### ISSUE THREAD

**Issue by y-ich** [TomMD/FixedPoint#1]
Hi. Thank you for your convenient package.

Could you help me?
I want to use odd, big word type(for example, Word65).
So I thought that a combination of your package and OddWord package is good for it.
The following code is the one I tried.

```
module Example where
import Data.Word
import Data.Word.Odd
import Data.FixedPoint

type Word65 = BigWord Word1 Word64
a = 1 :: Word65
```

and encountered the following error

```
No instance for (Data.Bits.FiniteBits (OddWord Word8 (One ())))
  arising from the literal ‘1’
In the expression: 1 :: Word65
In an equation for ‘a’: a = 1 :: Word65
```

If you use Word8 instead of Word1, no error.
I wonder that Word1 and Word64 are certainly instances of Num but Word65 may not be an instance of Num.

How can I avoid this problem?

**Comment by TomMD** [comment]
I've never heard of OddWord, but it appears you could just add a FiniteBits instance for `OddWord Word8 (One ())`.  This will probably require some CPP to make it work with a suitable set of GHC compiler versions and thus be an acceptable pull request to the author.

**Comment by y-ich** [comment]
Thank you for your quick reply.
According to your advice, adding the following code solved the problem!

instance (Bits a, Num a, TypeNum n) => FiniteBits (OddWord a n) where
    finiteBitSize = bitSize

Thank you!

**Comment by TomMD** [comment]
Happy to help.
